"""Generates every brand asset from one geometry: "la tilde subrayada".

The mark is a Young Serif lowercase "a" whose acute accent is a highlighter
stroke. Run from the repo root after changing the geometry or the palette:

    pip install fonttools pillow
    python tool/brand_assets.py
    dart run flutter_native_splash:create

Outputs (all overwritten):
    brand/logo.svg                        master, full colour on Tinta
    brand/logo-mono.svg                   single colour, transparent
    brand/play-icon-512.png               Play Store listing icon
    brand/play-icon-1024.png              preview
    docs/og.png                           link preview (WhatsApp, redes), 1200x630
    assets/branding/splash_logo.png       native splash (flutter_native_splash)
    android/.../drawable/ic_launcher_foreground.xml   adaptive icon, colour
    android/.../drawable/ic_launcher_monochrome.xml   adaptive icon, themed
    android/.../drawable/ic_notification.xml          status bar silhouette
    android/.../mipmap-*/ic_launcher(.png|_round.png) legacy icons (API 24-25)
"""

from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
FONT = ROOT / "assets/fonts/YoungSerif-Regular.ttf"
RES = ROOT / "android/app/src/main/res"

INK = "#14213D"
HIGHLIGHTER = "#FFE14A"
PAPER = "#F4F6FA"

# All geometry lives in a 108x108 box: the adaptive-icon canvas. Its safe
# zone is the central 66 units, so the mark is kept inside ~21..87.
BOX = 108.0
GLYPH_WIDTH = 38.0
GLYPH_CENTER_X = 54.0
GLYPH_BASELINE = 80.0


def glyph_path() -> tuple[str, tuple[float, float, float, float]]:
    """SVG path data of the "a" in the 108 box, plus its bounds there."""
    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("a")]
    bounds = BoundsPen(glyphs)
    glyphs[name].draw(bounds)
    x0, y0, x1, y1 = bounds.bounds
    scale = GLYPH_WIDTH / (x1 - x0)
    dx = GLYPH_CENTER_X - (x0 + x1) / 2 * scale
    # Font units are y-up; the box is y-down.
    transform = (scale, 0, 0, -scale, dx, GLYPH_BASELINE)
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
    glyphs[name].draw(TransformPen(pen, transform))
    top = GLYPH_BASELINE - y1 * scale
    return pen.getCommands(), (dx + x0 * scale, top, dx + x1 * scale, GLYPH_BASELINE)


def accent_polygon(glyph_top: float) -> list[tuple[float, float]]:
    """The highlighter stroke: a chisel-tip parallelogram rising to the right,
    where the acute accent would be."""
    left, right = GLYPH_CENTER_X - 11, GLYPH_CENTER_X + 15
    low = glyph_top - 4
    rise, thick = 11.0, 8.5
    return [
        (left, low),
        (right, low - rise),
        (right + 1.5, low - rise - thick),
        (left + 1.5, low - thick),
    ]


def poly_path(points: list[tuple[float, float]]) -> str:
    head, *rest = points
    return f"M{head[0]:.2f} {head[1]:.2f}" + "".join(
        f"L{x:.2f} {y:.2f}" for x, y in rest
    ) + "Z"


def svg(glyph: str, accent: str, *, bg: str | None, fg: str, mark: str) -> str:
    rect = f'<rect width="{BOX:g}" height="{BOX:g}" fill="{bg}"/>' if bg else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX:g} {BOX:g}">'
        f'{rect}<path d="{accent}" fill="{mark}"/><path d="{glyph}" fill="{fg}"/></svg>\n'
    )


def vector(paths: list[tuple[str, str]], *, size: int = 108, box: float = BOX,
           offset: float = 0) -> str:
    items = "".join(
        f'\n        <path android:fillColor="{c}" android:pathData="{d}"/>' for d, c in paths
    )
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by tool/brand_assets.py. Do not edit by hand. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size}dp" android:height="{size}dp"\n'
        f'    android:viewportWidth="{box:g}" android:viewportHeight="{box:g}">\n'
        f'    <group android:translateX="{offset:g}" android:translateY="{offset:g}">'
        f"{items}\n    </group>\n</vector>\n"
    )


def raster(size: int, *, bg: str | None, round_mask: bool = False,
           zoom: float = 1.0) -> Image.Image:
    """Draws the mark with PIL at 4x and downsamples, for smooth edges."""
    from fontTools.pens.recordingPen import RecordingPen  # noqa: F401

    big = size * 4
    s = big / BOX * zoom
    off = big / 2 - BOX / 2 * s
    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if bg:
        if round_mask:
            d.ellipse((0, 0, big - 1, big - 1), fill=bg)
        else:
            d.rectangle((0, 0, big, big), fill=bg)
    d.polygon([(x * s + off, y * s + off) for x, y in ACCENT], fill=HIGHLIGHTER)
    for contour in GLYPH_POLYS:
        d.polygon([(x * s + off, y * s + off) for x, y in contour],
                  fill=PAPER if bg else INK)
    # Counters (holes) are drawn back in the background colour.
    for contour in GLYPH_HOLES:
        d.polygon([(x * s + off, y * s + off) for x, y in contour],
                  fill=bg or (0, 0, 0, 0))
    return img.resize((size, size), Image.LANCZOS)


def flatten_glyph() -> tuple[list, list]:
    """Glyph contours as polygons (curves sampled), split into outer shapes
    and holes by winding direction."""
    from fontTools.pens.basePen import BasePen

    class Flat(BasePen):
        def __init__(self, gs):
            super().__init__(gs)
            self.contours, self.cur = [], []

        def _moveTo(self, p):
            self.cur = [p]

        def _lineTo(self, p):
            self.cur.append(p)

        def _curveToOne(self, p1, p2, p3):
            p0 = self.cur[-1]
            for i in range(1, 13):
                t = i / 12
                mt = 1 - t
                self.cur.append((
                    mt**3 * p0[0] + 3 * mt * mt * t * p1[0] + 3 * mt * t * t * p2[0] + t**3 * p3[0],
                    mt**3 * p0[1] + 3 * mt * mt * t * p1[1] + 3 * mt * t * t * p2[1] + t**3 * p3[1],
                ))

        def _qCurveToOne(self, p1, p2):
            p0 = self.cur[-1]
            for i in range(1, 9):
                t = i / 8
                mt = 1 - t
                self.cur.append((
                    mt * mt * p0[0] + 2 * mt * t * p1[0] + t * t * p2[0],
                    mt * mt * p0[1] + 2 * mt * t * p1[1] + t * t * p2[1],
                ))

        def _closePath(self):
            self.contours.append(self.cur)
            self.cur = []

    font = TTFont(FONT)
    glyphs = font.getGlyphSet()
    name = font.getBestCmap()[ord("a")]
    bounds = BoundsPen(glyphs)
    glyphs[name].draw(bounds)
    x0, _, x1, _ = bounds.bounds
    scale = GLYPH_WIDTH / (x1 - x0)
    dx = GLYPH_CENTER_X - (x0 + x1) / 2 * scale
    flat = Flat(glyphs)
    glyphs[name].draw(TransformPen(flat, (scale, 0, 0, -scale, dx, GLYPH_BASELINE)))
    outer, holes = [], []
    for c in flat.contours:
        area = sum(c[i][0] * c[(i + 1) % len(c)][1] - c[(i + 1) % len(c)][0] * c[i][1]
                   for i in range(len(c)))
        (outer if area > 0 else holes).append(c)
    if not outer:  # winding convention differs: the biggest one is the outline
        outer, holes = holes[:1], holes[1:]
    return outer, holes


GLYPH, GLYPH_BOUNDS = glyph_path()
ACCENT = accent_polygon(GLYPH_BOUNDS[1])
ACCENT_PATH = poly_path(ACCENT)
GLYPH_POLYS, GLYPH_HOLES = flatten_glyph()


def main() -> None:
    brand = ROOT / "brand"
    brand.mkdir(exist_ok=True)
    (brand / "logo.svg").write_text(
        svg(GLYPH, ACCENT_PATH, bg=INK, fg=PAPER, mark=HIGHLIGHTER), encoding="utf8")
    (brand / "logo-mono.svg").write_text(
        svg(GLYPH, ACCENT_PATH, bg=None, fg=INK, mark=INK), encoding="utf8")

    drawable = RES / "drawable"
    (drawable / "ic_launcher_foreground.xml").write_text(
        vector([(ACCENT_PATH, HIGHLIGHTER), (GLYPH, PAPER)]), encoding="utf8")
    (drawable / "ic_launcher_monochrome.xml").write_text(
        vector([(ACCENT_PATH, "#FFFFFFFF"), (GLYPH, "#FFFFFFFF")]), encoding="utf8")
    # Status bar icon: 24dp, the mark zoomed so it fills the frame. Android
    # only reads its alpha.
    (drawable / "ic_notification.xml").write_text(
        vector([(ACCENT_PATH, "#FFFFFFFF"), (GLYPH, "#FFFFFFFF")],
               size=24, box=62, offset=-23),
        encoding="utf8")

    raster(512, bg=INK).convert("RGB").save(brand / "play-icon-512.png")
    raster(1024, bg=INK).convert("RGB").save(brand / "play-icon-1024.png")
    # Splash: the mark on a transparent canvas; flutter_native_splash paints
    # the Tinta background around it.
    raster(1152, bg=None, zoom=1.0).save(ROOT / "assets/branding/splash_logo.png")

    og_image().save(ROOT / "docs/og.png", optimize=True)

    legacy = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
    for density, px in legacy.items():
        folder = RES / f"mipmap-{density}"
        for old in folder.glob("ic_launcher*"):
            old.unlink()
        raster(px, bg=INK, zoom=1.35).save(folder / "ic_launcher.png")
        raster(px, bg=INK, round_mask=True, zoom=1.35).save(folder / "ic_launcher_round.png")


def og_image() -> Image.Image:
    """Link preview: the mark and the promise, on Tinta."""
    from PIL import ImageFont

    w, h = 1200, 630
    img = Image.new("RGB", (w, h), INK)
    mark = raster(420, bg=INK)
    img.paste(mark, (40, 105))
    d = ImageDraw.Draw(img)
    serif = ImageFont.truetype(str(FONT), 78)
    sans = ImageFont.truetype(str(ROOT / "assets/fonts/Figtree-Medium.ttf"), 34)
    x = 470
    d.text((x, 170), "Datos raros", font=serif, fill=PAPER)
    box = d.textbbox((x, 270), "que son verdad.", font=serif)
    d.rectangle((box[0] - 8, box[1] - 4, box[2] + 8, box[3] + 10), fill=HIGHLIGHTER)
    d.text((x, 270), "que son verdad.", font=serif, fill=INK)
    d.text((x, 410), "Ajá · cada respuesta, con su fuente", font=sans, fill="#9AA5BB")
    return img


if __name__ == "__main__":
    main()
